server:
  port: 8800
spring:
  application:
    name: cloud-client
eureka:
  instance:
    hostname: localhost
    instance-id: http://localhost:8800
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #去哪里注册，eureka服务地址